# profiles.yml
airbyte_dbt:
  target: dev

  outputs:
    dev:
      type: postgres
      threads: 4
      host: 127.0.0.1
      port: 9131
      user: postgres
      pass: postgres
      dbname: PostgresTB1
      schema: public

    # prod:
    #   type: postgres
    #   threads: [1 or more]
    #   host: [host]
    #   port: [port]
    #   user: [prod_username]
    #   pass: [prod_password]
    #   dbname: [dbname]
    #   schema: [prod_schema]
